# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='category',
            field=models.CharField(choices=[(b'artposts', b'ARTPOSTS'), (b'itposts', b'ITPOSTS')], default=b'itposts', max_length=6),
        ),
    ]
