# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userblog', '0003_auto_20180205_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpost',
            options={},
        ),
    ]
