# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblog', '0004_auto_20180206_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='category',
            field=models.IntegerField(default=b'1'),
        ),
    ]
