# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblog', '0005_auto_20180206_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsPermisssion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('1', 'IT Posts displayed'), ('2', 'Art posts displayed')),
            },
        ),
        migrations.AlterField(
            model_name='userpost',
            name='category',
            field=models.IntegerField(choices=[(b'1', b'ITPOSTS'), (b'2', b'ARTPOSTS')], default=b'1'),
        ),
    ]
