# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblog', '0006_auto_20180206_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postspermisssion',
            options={'permissions': (('itposts', 'IT Posts displayed'), ('artposts', 'Art posts displayed'))},
        ),
        migrations.AlterField(
            model_name='userpost',
            name='category',
            field=models.CharField(choices=[(b'1', b'ITPOSTS'), (b'2', b'ARTPOSTS')], default=b'itposts', max_length=6),
        ),
    ]
